optional java + corrected memory corruption in src/ac/validate.c
git-svn-id: https://svn.forge.cnaf.infn.it/svn/voms/voms/trunk@267 5daf30ca-8a0d-0410-8b79-804c1d55056c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -468,7 +468,7 @@ ac_includes_default="\
 #endif"
 
 ac_default_prefix="/opt/glite"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT WORKDIR WANT_UNIT_TEST_TRUE WANT_UNIT_TEST_FALSE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL NO_GLOBUS_FLAGS OPENSSL_LIBS ALLOCA LIBOBJS ENABLE_GLITE_TRUE ENABLE_GLITE_FALSE DISTTAR LOCATION_ENV LOCATION_DIR VAR_LOCATION_ENV GLITE_LOCATION GLITE_CFLAGS EXPAT_INSTALL_PATH EXPAT_CFLAGS EXPAT_LIBS EXPAT_STATIC_LIBS CPPUNIT_CFLAGS CPPUNIT_LIBS WANTED_OLDGAA_LIBS WANTED_SSL_UTILS_LIBS WANTED_SOCK_LIBS WANTED_API_LIBS WANTED_ATTCERT_LIBS GLOBUS_CFLAGS GLOBUS_GCC32_CFLAGS GLOBUS_GCC32DBG_CFLAGS GLOBUS_GCC32DBGPTHR_CFLAGS GLOBUS_GCC32PTHR_CFLAGS GLOBUS_GCC64_CFLAGS GLOBUS_GCC64DBG_CFLAGS GLOBUS_GCC64DBGPTHR_CFLAGS GLOBUS_GCC64PTHR_CFLAGS GLOBUS_GSS_LIBS GLOBUS_GCC32_GSS_LIBS GLOBUS_GCC32DBG_GSS_LIBS GLOBUS_GCC32DBGPTHR_GSS_LIBS GLOBUS_GCC32PTHR_GSS_LIBS GLOBUS_GCC64_GSS_LIBS GLOBUS_GCC64DBG_GSS_LIBS GLOBUS_GCC64DBGPTHR_GSS_LIBS GLOBUS_GCC64PTHR_GSS_LIBS BUILD_DOCS_TRUE BUILD_DOCS_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT WORKDIR WANT_UNIT_TEST_TRUE WANT_UNIT_TEST_FALSE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL NO_GLOBUS_FLAGS OPENSSL_LIBS ALLOCA LIBOBJS ENABLE_GLITE_TRUE ENABLE_GLITE_FALSE DISTTAR LOCATION_ENV LOCATION_DIR VAR_LOCATION_ENV GLITE_LOCATION GLITE_CFLAGS EXPAT_INSTALL_PATH EXPAT_CFLAGS EXPAT_LIBS EXPAT_STATIC_LIBS CPPUNIT_CFLAGS CPPUNIT_LIBS WANTED_OLDGAA_LIBS WANTED_SSL_UTILS_LIBS WANTED_SOCK_LIBS WANTED_API_LIBS WANTED_ATTCERT_LIBS GLOBUS_CFLAGS GLOBUS_GCC32_CFLAGS GLOBUS_GCC32DBG_CFLAGS GLOBUS_GCC32DBGPTHR_CFLAGS GLOBUS_GCC32PTHR_CFLAGS GLOBUS_GCC64_CFLAGS GLOBUS_GCC64DBG_CFLAGS GLOBUS_GCC64DBGPTHR_CFLAGS GLOBUS_GCC64PTHR_CFLAGS GLOBUS_GSS_LIBS GLOBUS_GCC32_GSS_LIBS GLOBUS_GCC32DBG_GSS_LIBS GLOBUS_GCC32DBGPTHR_GSS_LIBS GLOBUS_GCC32PTHR_GSS_LIBS GLOBUS_GCC64_GSS_LIBS GLOBUS_GCC64DBG_GSS_LIBS GLOBUS_GCC64DBGPTHR_GSS_LIBS GLOBUS_GCC64PTHR_GSS_LIBS BUILD_DOCS_TRUE BUILD_DOCS_FALSE BUILD_JAVA_TRUE BUILD_JAVA_FALSE JAVA_INCLUDES LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1043,6 +1043,7 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-glite     enable gLite
  --enable-docs Enable doc generation
+  --enable-java   Enable compilation of the Java libraries
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1061,6 +1062,7 @@ Optional Packages:
   --with-cppunit-prefix=PFX prefix where 'cppunit' is installed.
   --with-globus-prefix=PFX     prefix where GLOBUS is installed. (/opt/globus)
   --with-globus-flavor=flavor default=$default_flavor
+ --with-java-home=<dir>    Specifies where to find the java installation, default=$JAVA_HOME
   --with-dmalloc          use dmalloc, as in
 			  http://www.dmalloc.com/dmalloc.tar.gz
 
@@ -4570,7 +4572,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4573 "configure"' > conftest.$ac_ext
+  echo '#line 4575 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5451,7 +5453,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5454:" \
+echo "$as_me:5456:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6549,11 +6551,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6554: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6556: \$? = $ac_status" >&5
+   echo "$as_me:6558: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6811,11 +6813,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6814: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6816: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6818: \$? = $ac_status" >&5
+   echo "$as_me:6820: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6873,11 +6875,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6876: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6878: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6880: \$? = $ac_status" >&5
+   echo "$as_me:6882: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9108,7 +9110,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9111 "configure"
+#line 9113 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9206,7 +9208,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9209 "configure"
+#line 9211 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11454,11 +11456,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11457: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11459: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11461: \$? = $ac_status" >&5
+   echo "$as_me:11463: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11516,11 +11518,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11519: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11521: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11523: \$? = $ac_status" >&5
+   echo "$as_me:11525: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12881,7 +12883,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12884 "configure"
+#line 12886 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12979,7 +12981,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12982 "configure"
+#line 12984 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13864,11 +13866,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13867: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13869: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13871: \$? = $ac_status" >&5
+   echo "$as_me:13873: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13926,11 +13928,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13929: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13931: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13933: \$? = $ac_status" >&5
+   echo "$as_me:13935: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16043,11 +16045,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16046: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16048: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16050: \$? = $ac_status" >&5
+   echo "$as_me:16052: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16305,11 +16307,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16308: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16310: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16312: \$? = $ac_status" >&5
+   echo "$as_me:16314: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16367,11 +16369,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16370: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16372: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16374: \$? = $ac_status" >&5
+   echo "$as_me:16376: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18602,7 +18604,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18605 "configure"
+#line 18607 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18700,7 +18702,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18703 "configure"
+#line 18705 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19787,7 +19789,7 @@ fi;
 # Check whether --with-openssl_prefix or --without-openssl_prefix was given.
 if test "${with_openssl_prefix+set}" = set; then
   withval="$with_openssl_prefix"
-
+  with_openssl_prefix="$withval"
 else
   with_openssl_prefix=/usr
 fi;
@@ -23935,7 +23937,7 @@ echo "${ECHO_T}$ac_cv_cppunit_valid" >&6
 # Check whether --with-globus_prefix or --without-globus_prefix was given.
 if test "${with_globus_prefix+set}" = set; then
   withval="$with_globus_prefix"
-
+  with_globus_prefix="$withval"
 else
   with_globus_prefix=${GLOBUS_LOCATION:-/opt/globus}
 fi;
@@ -23968,7 +23970,7 @@ echo $ECHO_N "checking for GLOBUS flavors... $ECHO_C" >&6
 # Check whether --with-globus_flavor or --without-globus_flavor was given.
 if test "${with_globus_flavor+set}" = set; then
   withval="$with_globus_flavor"
-
+  with_globus_flavor="$withval"
 else
   with_globus_flavor=${GLOBUS_FLAVOR:-${default_flavor}}
 fi;
@@ -24159,6 +24161,54 @@ else
   BUILD_DOCS_FALSE=
 fi
 
+
+
+
+  # Check whether --enable-java or --disable-java was given.
+if test "${enable_java+set}" = set; then
+  enableval="$enable_java"
+
+      case "$enableval" in
+      yes) build_java="yes" ;;
+      no)  build_java="no" ;;
+      *) { { echo "$as_me:$LINENO: error: bad value $(enableval) for --enable-java" >&5
+echo "$as_me: error: bad value $(enableval) for --enable-java" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+
+else
+   have_java="yes"
+fi;
+
+
+
+if test x$have_java = xyes; then
+  BUILD_JAVA_TRUE=
+  BUILD_JAVA_FALSE='#'
+else
+  BUILD_JAVA_TRUE='#'
+  BUILD_JAVA_FALSE=
+fi
+
+
+  if test "x$have_java" = "xyes"; then
+    echo "$as_me:$LINENO: checking for JAVA" >&5
+echo $ECHO_N "checking for JAVA... $ECHO_C" >&6
+
+# Check whether --with-java-home or --without-java-home was given.
+if test "${with_java_home+set}" = set; then
+  withval="$with_java_home"
+   javahome="$withval"
+else
+   javahome="$JAVA_HOME"
+fi;
+# Find include dirs
+    javainc="`find $javahome/include -type d -exec echo -n '-I{} ' ';'`"
+    JAVA_INCLUDES="$javainc"
+    echo "$as_me:$LINENO: result: $javahome" >&5
+echo "${ECHO_T}$javahome" >&6
+
+  fi
 
 
 
@@ -25657,6 +25707,13 @@ echo "$as_me: error: conditional \"BUILD_DOCS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_JAVA_TRUE}" && test -z "${BUILD_JAVA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_JAVA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_JAVA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -26333,6 +26390,9 @@ s,@GLOBUS_GCC64DBGPTHR_GSS_LIBS@,$GLOBUS_GCC64DBGPTHR_GSS_LIBS,;t t
 s,@GLOBUS_GCC64PTHR_GSS_LIBS@,$GLOBUS_GCC64PTHR_GSS_LIBS,;t t
 s,@BUILD_DOCS_TRUE@,$BUILD_DOCS_TRUE,;t t
 s,@BUILD_DOCS_FALSE@,$BUILD_DOCS_FALSE,;t t
+s,@BUILD_JAVA_TRUE@,$BUILD_JAVA_TRUE,;t t
+s,@BUILD_JAVA_FALSE@,$BUILD_JAVA_FALSE,;t t
+s,@JAVA_INCLUDES@,$JAVA_INCLUDES,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
